services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nimbus-server-local-compose
    restart: unless-stopped
    env_file: .env
    environment:
      NODE_ENV: production
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/nimbus
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
